services:
  app:
    image: docker24ducanh24/car-parking-management_app:1.0
    ports:
      - 3000:3000

  server:
    image: docker24ducanh24/car-parking-management_api:1.0
    ports:
      - 3001:3001